### ISSUE TITLE
decide about the hardware license

### ISSUE THREAD

**Issue by derikon** [derikon/TactJam#1]
Hardware design, PCB schematics, and supplementary materials should be licensed under creative commons. Which type is suitable, e.g. public domain?

**Comment by derikon** [comment]
Here are some basic considerations to be taken into account: [https://opensource.guide/legal/](https://opensource.guide/legal/)

What about the combination of multiple licenses in one project - one for code and another for schematics, CAD-files, etc.?

**Comment by freitaggeorg** [comment]
Maybe we can ask Lucas here, if he has already seriously studied this topic.

**Comment by derikon** [comment]
We can use multiple licenses in a single project. It's good pratice to add a license-file in the root directory that provides further information about the licenses for certain sub-directories.

**Comment by derikon** [comment]
I would use [CC-BY](https://creativecommons.org/licenses/by/4.0/)
