### ISSUE TITLE
What platform do we use?

### ISSUE THREAD

**Issue by derikon** [derikon/TactJam#10]
Since we want users to open and save files quickly while being able to share it with others, we need a multi-OS tool so either Web or Java-based would make our task simple.
In my opinion, Processing is a good choice in this case. We can ask the participants to simply download it (relatively light ~130MB) and run the scripts we will provide. It enables having a simple interface and it connects super easily to the serial port for communicating with the device.

**Comment by bfrucha** [comment]
Let's use [Processing](https://processing.org/). It seems to be the best solution in my opinion.
