### ISSUE TITLE
Can we play tactons without touching the physical interface of TactJam (like potentiometers)?

### ISSUE THREAD

**Issue by derikon** [derikon/TactJam#11]
Need to be careful how we design the hardware to be sure we can play tactons without the user being involved.

**Comment by derikon** [comment]
Yes, there should be somekind of menu to select recorded tactons and ply them back. During playback we "disable" all buttons that may lead to unintended modification.

**Comment by freitaggeorg** [comment]
does the term 'play' here mean the replay of a recorded tacton?

**Comment by derikon** [comment]
@freitaggeorg yes, play back = replay
