### ISSUE TITLE
Create Webpage (GitHub pages)

### ISSUE THREAD

**Issue by derikon** [derikon/TactJam#13]
I already set up the webpage and a dedicated branch.

**Comment by source2k** [comment]
investigate template usage

**Comment by source2k** [comment]
fill page with information from proposal

**Comment by source2k** [comment]
TODO:
Move menu to sidebar
Remove Hyphenations from text
Update references (sections, tables, …)
Replace screenshotted images to real version (Upload images, Make image captions as real text)
Use more horizontal screen space
