### ISSUE TITLE
Build the software UI

### ISSUE THREAD

**Issue by bfrucha** [derikon/TactJam#18]
We'll use [G4P ](http://www.lagers.org.uk/g4p/index.html) to build the UI in Processing. Seems to be the easiest and quickest way.

Here is an early possible [design of the interface](https://github.com/derikon/TactJam/blob/master/software/Design%20samples/software_early-design2.jpg).

**Comment by derikon** [comment]
Looks promising!

**Comment by freitaggeorg** [comment]
Is the approach with procession still current or has it become a new technology?

**Comment by bfrucha** [comment]
We switch to [Electron](https://www.electronjs.org/). A first mock-up of the application can be accessed [here](https://github.com/derikon/TactJam/tree/develop/software/GUI%20(Electron)).
