### ISSUE TITLE
decide about the software license

### ISSUE THREAD

**Issue by derikon** [derikon/TactJam#2]
Software should be licensed under Open Source. Which one is suitable, e.g. MIT?

**Comment by derikon** [comment]
Here are some basic considerations to be taken into account: [https://opensource.guide/legal/](https://opensource.guide/legal/)

What about the combination of multiple licenses in one project - one for code and another for schematics, CAD-files, etc.?

**Comment by freitaggeorg** [comment]
The same approach as with the hardware - ask Lucas :)

**Comment by derikon** [comment]
We can use multiple licenses in a single project. It's good pratice to add a license-file in the root directory that provides further information about the licenses for certain sub-directories.

**Comment by derikon** [comment]
I would use the [MIT license](https://choosealicense.com/licenses/mit/) for our software.
