### ISSUE TITLE
documenting placement of actuators

### ISSUE THREAD

**Issue by derikon** [derikon/TactJam#4]
How do participants document their actuator setup for each tacton? This is important in terms of reproducibility.

**Comment by Hypnozk** [comment]
Google doc with the possibilites(pros,cons) https://docs.google.com/document/d/16SL6cMSfG9839DYE07V-BWFXGv0OAmQ8QSwlcOuKfSk/edit?usp=sharing

**Comment by Hypnozk** [comment]
decision 4 prepared; because it's easy to handle and high usability

**Comment by derikon** [comment]
@Hypnozk, could you edit your last comment and add some more information about number 4? That will help people who don't have access to the document. Thanks

**Comment by Hypnozk** [comment]
next steps: decide how to implement the choosen option; it would be possible to show the sketches on a pc software or use maybe other programs there you could work together on the positions

**Comment by Hypnozk** [comment]
we decide to prefer to mark the actuators on a sketch in the pc software; but there are some remaining questions on the behaviof functions of the software
next steps: define the functional requests for the software
