### ISSUE TITLE
Solder areas are too small

### ISSUE THREAD

**Issue by derikon** [derikon/TactJam#46]
Check and fix the issues in the PCB layout.

<img width="875" alt="Screenshot 2020-12-04 at 09 59 22" src="https://user-images.githubusercontent.com/3382491/101143630-74ffc900-3617-11eb-9d4b-e976512315d4.png">

**Comment by M6QF** [comment]
Uploaded updated version (v. 0.2.1):
- Resistor networks removed
- 1K resistors (0603) added
