### ISSUE TITLE
varying intensity of actuators

### ISSUE THREAD

**Issue by derikon** [derikon/TactJam#5]
## Question

Should we consider varying the actuators' intensity in record mode?

## Ideas

1. enable a potentiometer to vary the intensity while playing live
2. first, record "the beat" and modulate the intensity in a second pass while playing back "the beat" (e.g. in loop with overdubbing) an record the intensity modulation solely
3. use force sensitive resistors (read pressure and map it to intensity levels) instead of push buttons

**Comment by freitaggeorg** [comment]
Setting the intensity is, in my opinion, a relevant option for Tacton design. On the other hand, the focus is on the temporal sequence of the individual actuators. For this reason, I find option 2 most useful. Creating the beat and then modulating it in a separate step.

**Comment by derikon** [comment]
In the last meeting we talked about this topic. We "decided" to focus on location and time (rhythm) and don't allow a second pass for modulations. But that can still be discussed.

**Comment by derikon** [comment]
# We will roll back to the two-pass strategy

1. record rhythm wit a global intensity value
2. [optional] record modulation of the intensity

Intensity values can be changed via a potentiometer or a slider.
