### ISSUE TITLE
Choose the encoding for Tactons

### ISSUE THREAD

**Issue by derikon** [derikon/TactJam#6]
What are the variables we are using? (time, frequency, amplitude?)

**Comment by derikon** [comment]
For ERMs the frequency and amplitude are linear dependent. So we can only control them simultaneously (_intensity_).

- time (or time stamps)
- intensity

**Comment by freitaggeorg** [comment]
The variation of the frequency separately from the amplitude requires expert knowledge. For the target group it may therefore make more sense to consider the two aspects as one.

Therefore time, amplitude and location (number of the actuator) are the relevant parameters
